title: Evaluation Service API
description: Portfolio and documentation site for the Evaluation Service API
theme: jekyll-theme-cayman
baseurl: "/eaas-app-doc"
url: "https://pratikdimble.github.io"
markdown: kramdown
